<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eric Song">

<title>Homework5</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework5</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eric Song </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="task-1" class="level2">
<h2 class="anchored" data-anchor-id="task-1">Task 1</h2>
<p><strong>Original Code</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>d1<span class="ot">=</span><span class="fu">read.table</span>(<span class="st">"student-mat.csv"</span>,<span class="at">sep=</span><span class="st">";"</span>,<span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>d2<span class="ot">=</span><span class="fu">read.table</span>(<span class="st">"student-por.csv"</span>,<span class="at">sep=</span><span class="st">";"</span>,<span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>d3<span class="ot">=</span><span class="fu">merge</span>(d1,d2,<span class="at">by=</span><span class="fu">c</span>(<span class="st">"school"</span>,<span class="st">"sex"</span>,<span class="st">"age"</span>,<span class="st">"address"</span>,<span class="st">"famsize"</span>,<span class="st">"Pstatus"</span>,<span class="st">"Medu"</span>,<span class="st">"Fedu"</span>,<span class="st">"Mjob"</span>,<span class="st">"Fjob"</span>,<span class="st">"reason"</span>,<span class="st">"nursery"</span>,<span class="st">"internet"</span>))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(d3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   382 obs. of  53 variables:
 $ school      : chr  "GP" "GP" "GP" "GP" ...
 $ sex         : chr  "F" "F" "F" "F" ...
 $ age         : int  15 15 15 15 15 15 15 15 15 15 ...
 $ address     : chr  "R" "R" "R" "R" ...
 $ famsize     : chr  "GT3" "GT3" "GT3" "GT3" ...
 $ Pstatus     : chr  "T" "T" "T" "T" ...
 $ Medu        : int  1 1 2 2 3 3 3 2 3 3 ...
 $ Fedu        : int  1 1 2 4 3 4 4 2 1 3 ...
 $ Mjob        : chr  "at_home" "other" "at_home" "services" ...
 $ Fjob        : chr  "other" "other" "other" "health" ...
 $ reason      : chr  "home" "reputation" "reputation" "course" ...
 $ nursery     : chr  "yes" "no" "yes" "yes" ...
 $ internet    : chr  "yes" "yes" "no" "yes" ...
 $ guardian.x  : chr  "mother" "mother" "mother" "mother" ...
 $ traveltime.x: int  2 1 1 1 2 1 2 2 2 1 ...
 $ studytime.x : int  4 2 1 3 3 3 3 2 4 4 ...
 $ failures.x  : int  1 2 0 0 2 0 2 0 0 0 ...
 $ schoolsup.x : chr  "yes" "yes" "yes" "yes" ...
 $ famsup.x    : chr  "yes" "yes" "yes" "yes" ...
 $ paid.x      : chr  "yes" "no" "yes" "yes" ...
 $ activities.x: chr  "yes" "no" "yes" "yes" ...
 $ higher.x    : chr  "yes" "yes" "yes" "yes" ...
 $ romantic.x  : chr  "no" "yes" "no" "no" ...
 $ famrel.x    : int  3 3 4 4 4 4 4 4 4 4 ...
 $ freetime.x  : int  1 3 3 3 2 3 2 1 4 3 ...
 $ goout.x     : int  2 4 1 2 1 2 2 3 2 3 ...
 $ Dalc.x      : int  1 2 1 1 2 1 2 1 2 1 ...
 $ Walc.x      : int  1 4 1 1 3 1 2 3 3 1 ...
 $ health.x    : int  1 5 2 5 3 5 5 4 3 4 ...
 $ absences.x  : int  2 2 8 2 8 2 0 2 12 10 ...
 $ G1.x        : int  7 8 14 10 10 12 12 8 16 10 ...
 $ G2.x        : int  10 6 13 9 10 12 0 9 16 11 ...
 $ G3.x        : int  10 5 13 8 10 11 0 8 16 11 ...
 $ guardian.y  : chr  "mother" "mother" "mother" "mother" ...
 $ traveltime.y: int  2 1 1 1 2 1 2 2 2 1 ...
 $ studytime.y : int  4 2 1 3 3 3 3 2 4 4 ...
 $ failures.y  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ schoolsup.y : chr  "yes" "yes" "yes" "yes" ...
 $ famsup.y    : chr  "yes" "yes" "yes" "yes" ...
 $ paid.y      : chr  "yes" "no" "no" "no" ...
 $ activities.y: chr  "yes" "no" "yes" "yes" ...
 $ higher.y    : chr  "yes" "yes" "yes" "yes" ...
 $ romantic.y  : chr  "no" "yes" "no" "no" ...
 $ famrel.y    : int  3 3 4 4 4 4 4 4 4 4 ...
 $ freetime.y  : int  1 3 3 3 2 3 2 1 4 3 ...
 $ goout.y     : int  2 4 1 2 1 2 2 3 2 3 ...
 $ Dalc.y      : int  1 2 1 1 2 1 2 1 2 1 ...
 $ Walc.y      : int  1 4 1 1 3 1 2 3 3 1 ...
 $ health.y    : int  1 5 2 5 3 5 5 4 3 4 ...
 $ absences.y  : int  4 2 8 2 2 2 0 0 6 10 ...
 $ G1.y        : int  13 13 14 10 13 11 10 11 15 10 ...
 $ G2.y        : int  13 11 13 11 13 12 11 10 15 10 ...
 $ G3.y        : int  13 11 12 10 13 12 12 11 15 10 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">nrow</span>(d3)) <span class="co"># 382 students</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 382</code></pre>
</div>
</div>
<p><strong>Using inner join().</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>joined_d3 <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(d1,d2, </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"school"</span>, <span class="st">"sex"</span>, <span class="st">"age"</span>, <span class="st">"address"</span>, <span class="st">"famsize"</span>,<span class="st">"Pstatus"</span>,<span class="st">"Medu"</span>, <span class="st">"Fedu"</span>, <span class="st">"Mjob"</span>, <span class="st">"Fjob"</span>, <span class="st">"reason"</span>,<span class="st">"nursery"</span>,<span class="st">"internet"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in inner_join(d1, d2, by = c("school", "sex", "age", "address", : Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 79 of `x` matches multiple rows in `y`.
ℹ Row 79 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(joined_d3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   382 obs. of  53 variables:
 $ school      : chr  "GP" "GP" "GP" "GP" ...
 $ sex         : chr  "F" "F" "F" "F" ...
 $ age         : int  18 17 15 15 16 16 16 17 15 15 ...
 $ address     : chr  "U" "U" "U" "U" ...
 $ famsize     : chr  "GT3" "GT3" "LE3" "GT3" ...
 $ Pstatus     : chr  "A" "T" "T" "T" ...
 $ Medu        : int  4 1 1 4 3 4 2 4 3 3 ...
 $ Fedu        : int  4 1 1 2 3 3 2 4 2 4 ...
 $ Mjob        : chr  "at_home" "at_home" "at_home" "health" ...
 $ Fjob        : chr  "teacher" "other" "other" "services" ...
 $ reason      : chr  "course" "course" "other" "home" ...
 $ guardian.x  : chr  "mother" "father" "mother" "mother" ...
 $ traveltime.x: int  2 1 1 1 1 1 1 2 1 1 ...
 $ studytime.x : int  2 2 2 3 2 2 2 2 2 2 ...
 $ failures.x  : int  0 0 3 0 0 0 0 0 0 0 ...
 $ schoolsup.x : chr  "yes" "no" "yes" "no" ...
 $ famsup.x    : chr  "no" "yes" "no" "yes" ...
 $ paid.x      : chr  "no" "no" "yes" "yes" ...
 $ activities.x: chr  "no" "no" "no" "yes" ...
 $ nursery     : chr  "yes" "no" "yes" "yes" ...
 $ higher.x    : chr  "yes" "yes" "yes" "yes" ...
 $ internet    : chr  "no" "yes" "yes" "yes" ...
 $ romantic.x  : chr  "no" "no" "no" "yes" ...
 $ famrel.x    : int  4 5 4 3 4 5 4 4 4 5 ...
 $ freetime.x  : int  3 3 3 2 3 4 4 1 2 5 ...
 $ goout.x     : int  4 3 2 2 2 2 4 4 2 1 ...
 $ Dalc.x      : int  1 1 2 1 1 1 1 1 1 1 ...
 $ Walc.x      : int  1 1 3 1 2 2 1 1 1 1 ...
 $ health.x    : int  3 3 3 5 5 5 3 1 1 5 ...
 $ absences.x  : int  6 4 10 2 4 10 0 6 0 0 ...
 $ G1.x        : int  5 5 7 15 6 15 12 6 16 14 ...
 $ G2.x        : int  6 5 8 14 10 15 12 5 18 15 ...
 $ G3.x        : int  6 6 10 15 10 15 11 6 19 15 ...
 $ guardian.y  : chr  "mother" "father" "mother" "mother" ...
 $ traveltime.y: int  2 1 1 1 1 1 1 2 1 1 ...
 $ studytime.y : int  2 2 2 3 2 2 2 2 2 2 ...
 $ failures.y  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ schoolsup.y : chr  "yes" "no" "yes" "no" ...
 $ famsup.y    : chr  "no" "yes" "no" "yes" ...
 $ paid.y      : chr  "no" "no" "no" "no" ...
 $ activities.y: chr  "no" "no" "no" "yes" ...
 $ higher.y    : chr  "yes" "yes" "yes" "yes" ...
 $ romantic.y  : chr  "no" "no" "no" "yes" ...
 $ famrel.y    : int  4 5 4 3 4 5 4 4 4 5 ...
 $ freetime.y  : int  3 3 3 2 3 4 4 1 2 5 ...
 $ goout.y     : int  4 3 2 2 2 2 4 4 2 1 ...
 $ Dalc.y      : int  1 1 2 1 1 1 1 1 1 1 ...
 $ Walc.y      : int  1 1 3 1 2 2 1 1 1 1 ...
 $ health.y    : int  3 3 3 5 5 5 3 1 1 5 ...
 $ absences.y  : int  4 2 6 0 0 6 0 2 0 0 ...
 $ G1.y        : int  0 9 12 14 11 12 13 10 15 12 ...
 $ G2.y        : int  11 11 13 14 13 12 12 13 16 12 ...
 $ G3.y        : int  11 11 12 14 13 13 13 13 17 13 ...</code></pre>
</div>
</div>
<p>Many to many relationship warning on row 79. Our data is also split between non joined variables.</p>
<p><strong>All variables but no G1,G2,G3,Paid, and absences.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>final_d1 <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(d1, d2,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>              <span class="co">#joins everything but specified columns in setdiff</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">by =</span> <span class="fu">names</span>(d1) <span class="sc">|&gt;</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                <span class="fu">setdiff</span>(<span class="fu">c</span>(<span class="st">"G1"</span>, <span class="st">"G2"</span>, <span class="st">"G3"</span>, <span class="st">"paid"</span>, <span class="st">"absences"</span>))</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(final_d1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   320 obs. of  38 variables:
 $ school    : chr  "GP" "GP" "GP" "GP" ...
 $ sex       : chr  "F" "F" "F" "F" ...
 $ age       : int  18 17 15 16 16 16 17 15 15 15 ...
 $ address   : chr  "U" "U" "U" "U" ...
 $ famsize   : chr  "GT3" "GT3" "GT3" "GT3" ...
 $ Pstatus   : chr  "A" "T" "T" "T" ...
 $ Medu      : int  4 1 4 3 4 2 4 3 3 4 ...
 $ Fedu      : int  4 1 2 3 3 2 4 2 4 4 ...
 $ Mjob      : chr  "at_home" "at_home" "health" "other" ...
 $ Fjob      : chr  "teacher" "other" "services" "other" ...
 $ reason    : chr  "course" "course" "home" "home" ...
 $ guardian  : chr  "mother" "father" "mother" "father" ...
 $ traveltime: int  2 1 1 1 1 1 2 1 1 1 ...
 $ studytime : int  2 2 3 2 2 2 2 2 2 2 ...
 $ failures  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ schoolsup : chr  "yes" "no" "no" "no" ...
 $ famsup    : chr  "no" "yes" "yes" "yes" ...
 $ paid.x    : chr  "no" "no" "yes" "yes" ...
 $ activities: chr  "no" "no" "yes" "no" ...
 $ nursery   : chr  "yes" "no" "yes" "yes" ...
 $ higher    : chr  "yes" "yes" "yes" "yes" ...
 $ internet  : chr  "no" "yes" "yes" "no" ...
 $ romantic  : chr  "no" "no" "yes" "no" ...
 $ famrel    : int  4 5 3 4 5 4 4 4 5 3 ...
 $ freetime  : int  3 3 2 3 4 4 1 2 5 3 ...
 $ goout     : int  4 3 2 2 2 4 4 2 1 3 ...
 $ Dalc      : int  1 1 1 1 1 1 1 1 1 1 ...
 $ Walc      : int  1 1 1 2 2 1 1 1 1 2 ...
 $ health    : int  3 3 5 5 5 3 1 1 5 2 ...
 $ absences.x: int  6 4 2 4 10 0 6 0 0 0 ...
 $ G1.x      : int  5 5 15 6 15 12 6 16 14 10 ...
 $ G2.x      : int  6 5 14 10 15 12 5 18 15 8 ...
 $ G3.x      : int  6 6 15 10 15 11 6 19 15 9 ...
 $ paid.y    : chr  "no" "no" "no" "no" ...
 $ absences.y: int  4 2 0 0 6 0 2 0 0 2 ...
 $ G1.y      : int  0 9 14 11 12 13 10 15 12 14 ...
 $ G2.y      : int  11 11 14 13 12 12 13 16 12 14 ...
 $ G3.y      : int  11 11 14 13 13 13 13 17 13 14 ...</code></pre>
</div>
</div>
<p><strong>Picking School,Sex, Famsize, and Reason as our categorical variables.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>final_d1 <span class="ot">&lt;-</span> final_d1 <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">school =</span> <span class="fu">as.factor</span>(school),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> <span class="fu">as.factor</span>(sex),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">famsize =</span> <span class="fu">as.factor</span>(famsize),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">reason =</span> <span class="fu">as.factor</span>(reason)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(final_d1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   320 obs. of  38 variables:
 $ school    : Factor w/ 2 levels "GP","MS": 1 1 1 1 1 1 1 1 1 1 ...
 $ sex       : Factor w/ 2 levels "F","M": 1 1 1 1 2 2 1 2 2 1 ...
 $ age       : int  18 17 15 16 16 16 17 15 15 15 ...
 $ address   : chr  "U" "U" "U" "U" ...
 $ famsize   : Factor w/ 2 levels "GT3","LE3": 1 1 1 1 2 2 1 2 1 1 ...
 $ Pstatus   : chr  "A" "T" "T" "T" ...
 $ Medu      : int  4 1 4 3 4 2 4 3 3 4 ...
 $ Fedu      : int  4 1 2 3 3 2 4 2 4 4 ...
 $ Mjob      : chr  "at_home" "at_home" "health" "other" ...
 $ Fjob      : chr  "teacher" "other" "services" "other" ...
 $ reason    : Factor w/ 4 levels "course","home",..: 1 1 2 2 4 2 2 2 2 4 ...
 $ guardian  : chr  "mother" "father" "mother" "father" ...
 $ traveltime: int  2 1 1 1 1 1 2 1 1 1 ...
 $ studytime : int  2 2 3 2 2 2 2 2 2 2 ...
 $ failures  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ schoolsup : chr  "yes" "no" "no" "no" ...
 $ famsup    : chr  "no" "yes" "yes" "yes" ...
 $ paid.x    : chr  "no" "no" "yes" "yes" ...
 $ activities: chr  "no" "no" "yes" "no" ...
 $ nursery   : chr  "yes" "no" "yes" "yes" ...
 $ higher    : chr  "yes" "yes" "yes" "yes" ...
 $ internet  : chr  "no" "yes" "yes" "no" ...
 $ romantic  : chr  "no" "no" "yes" "no" ...
 $ famrel    : int  4 5 3 4 5 4 4 4 5 3 ...
 $ freetime  : int  3 3 2 3 4 4 1 2 5 3 ...
 $ goout     : int  4 3 2 2 2 4 4 2 1 3 ...
 $ Dalc      : int  1 1 1 1 1 1 1 1 1 1 ...
 $ Walc      : int  1 1 1 2 2 1 1 1 1 2 ...
 $ health    : int  3 3 5 5 5 3 1 1 5 2 ...
 $ absences.x: int  6 4 2 4 10 0 6 0 0 0 ...
 $ G1.x      : int  5 5 15 6 15 12 6 16 14 10 ...
 $ G2.x      : int  6 5 14 10 15 12 5 18 15 8 ...
 $ G3.x      : int  6 6 15 10 15 11 6 19 15 9 ...
 $ paid.y    : chr  "no" "no" "no" "no" ...
 $ absences.y: int  4 2 0 0 6 0 2 0 0 2 ...
 $ G1.y      : int  0 9 14 11 12 13 10 15 12 14 ...
 $ G2.y      : int  11 11 14 13 12 12 13 16 12 14 ...
 $ G3.y      : int  11 11 14 13 13 13 13 17 13 14 ...</code></pre>
</div>
</div>
</section>
<section id="task-2" class="level2">
<h2 class="anchored" data-anchor-id="task-2">Task 2</h2>
<section id="categorical-variables" class="level4">
<h4 class="anchored" data-anchor-id="categorical-variables">Categorical Variables</h4>
<p><strong>One-way contingency table</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>one_way_tbl <span class="ot">&lt;-</span> <span class="fu">table</span>(final_d1<span class="sc">$</span>school)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>one_way_tbl</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 GP  MS 
287  33 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>one_way_tbl[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> GP 
287 </code></pre>
</div>
</div>
<p>There are 287 students going to GP.</p>
<p><strong>Two-way contingency table</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>two_way_tbl <span class="ot">&lt;-</span> <span class="fu">table</span>(final_d1<span class="sc">$</span>school,final_d1<span class="sc">$</span>sex)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>two_way_tbl</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    
       F   M
  GP 153 134
  MS  21  12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>two_way_tbl[<span class="dv">1</span>,<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 153</code></pre>
</div>
</div>
<p>153 Female students go to GP.</p>
<p><strong>Three-way contingency table</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>three_way_tbl <span class="ot">&lt;-</span> <span class="fu">table</span>(final_d1<span class="sc">$</span>school,final_d1<span class="sc">$</span>sex,final_d1<span class="sc">$</span>famsize)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>three_way_tbl</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>, ,  = GT3

    
       F   M
  GP 115  93
  MS  15   7

, ,  = LE3

    
       F   M
  GP  38  41
  MS   6   5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>three_way_tbl[<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 115</code></pre>
</div>
</div>
<p>115 Female Students that go to GP come from a family greater than 3.</p>
<p><strong>Filter method:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>filter_d1 <span class="ot">&lt;-</span> final_d1 <span class="sc">|&gt;</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(school <span class="sc">==</span> <span class="st">"GP"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>cond_two_way <span class="ot">&lt;-</span><span class="fu">table</span>(filter_d1<span class="sc">$</span>sex,filter_d1<span class="sc">$</span>famsize)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>cond_two_way</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    GT3 LE3
  F 115  38
  M  93  41</code></pre>
</div>
</div>
<p><strong>Three way table method (using previous three way variable):</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>cond_three_way <span class="ot">&lt;-</span> three_way_tbl[<span class="st">"GP"</span>,,]</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>cond_three_way</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    GT3 LE3
  F 115  38
  M  93  41</code></pre>
</div>
</div>
<p><strong>Using group_by(),summarize(),and pivot_wider().</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>new_two_way <span class="ot">&lt;-</span> final_d1 <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">group_by</span>(school,sex) <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">summarize</span>(<span class="at">count=</span><span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">pivot_wider</span>(<span class="at">names_from=</span>sex,<span class="at">values_from=</span>count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'school'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>new_two_way</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
# Groups:   school [2]
  school     F     M
  &lt;fct&gt;  &lt;int&gt; &lt;int&gt;
1 GP       153   134
2 MS        21    12</code></pre>
</div>
</div>
<p><strong>Stacked bar graph</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span> final_d1 , <span class="fu">aes</span>(<span class="at">x =</span> reason, <span class="at">fill =</span> sex)) <span class="sc">+</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Stacked Bar Graph: Reason vs Sex"</span>,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"School"</span>,</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"# of Students"</span>,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Sex"</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Homework5_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Side by Side Graph.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span> final_d1 ,<span class="fu">aes</span>(<span class="at">x =</span> school, <span class="at">fill =</span> sex)) <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Side by Side Graph: School vs Sex"</span>,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"School"</span>,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"# of Students"</span>,</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Sex"</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Homework5_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="numeric-variables" class="level4">
<h4 class="anchored" data-anchor-id="numeric-variables">Numeric Variables</h4>
<p><strong>Single Grouping (by sex):</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>one_summary <span class="ot">&lt;-</span> final_d1 <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>              <span class="co">#combining G3s together</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>              <span class="fu">mutate</span>(<span class="at">new_G3 =</span> <span class="fu">rowMeans</span>(<span class="fu">cbind</span>(G3.x, G3.y), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>                <span class="fu">group_by</span>(sex) <span class="sc">|&gt;</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">summarise</span>(</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>                    <span class="co">#G3</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">mean_G3 =</span> <span class="fu">mean</span>(new_G3, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">median_G3 =</span> <span class="fu">median</span>(new_G3, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sd_G3 =</span> <span class="fu">sd</span>(new_G3, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>                    <span class="at">IQR_G3 =</span> <span class="fu">IQR</span>(new_G3, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>                    <span class="co">#Age</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>                    <span class="at">mean_age =</span> <span class="fu">mean</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>                    <span class="at">median_age =</span> <span class="fu">median</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sd_age =</span> <span class="fu">sd</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>                    <span class="at">IQR_age =</span> <span class="fu">IQR</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>                    <span class="co">#health</span></span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>                    <span class="at">mean_health =</span> <span class="fu">mean</span>(health, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>                    <span class="at">median_health =</span> <span class="fu">median</span>(health, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sd_health =</span> <span class="fu">sd</span>(health, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>                    <span class="at">IQR_health =</span> <span class="fu">IQR</span>(health, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>                   )</span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>one_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 13
  sex   mean_G3 median_G3 sd_G3 IQR_G3 mean_age median_age sd_age IQR_age
  &lt;fct&gt;   &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
1 F        11.9        12  3.01   4.38     16.6         17   1.06       1
2 M        12.1        12  3.23   4        16.4         16   1.22       2
# ℹ 4 more variables: mean_health &lt;dbl&gt;, median_health &lt;dbl&gt;, sd_health &lt;dbl&gt;,
#   IQR_health &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>Two grouping variables (Sex and School):</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>two_summary <span class="ot">&lt;-</span> final_d1 <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>                <span class="fu">mutate</span>(<span class="at">new_G2 =</span> <span class="fu">rowMeans</span>(<span class="fu">cbind</span>(G2.x, G2.y), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),<span class="at">new_absences =</span> <span class="fu">rowMeans</span>(<span class="fu">cbind</span>(absences.x, absences.y, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))) <span class="sc">|&gt;</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>                <span class="fu">group_by</span>(sex,school) <span class="sc">|&gt;</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">summarise</span>(</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>                    <span class="co">#G2</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">mean_G2 =</span> <span class="fu">mean</span>(new_G2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">median_G2 =</span> <span class="fu">median</span>(new_G2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sd_G2 =</span> <span class="fu">sd</span>(new_G2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">IQR_G2 =</span> <span class="fu">IQR</span>(new_G2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>                    <span class="co">#age</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>                    <span class="at">mean_age =</span> <span class="fu">mean</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>                    <span class="at">median_age =</span> <span class="fu">median</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sd_age =</span> <span class="fu">sd</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>                    <span class="at">IQR_age =</span> <span class="fu">IQR</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>                    <span class="co">#absences (another split variable with x/y datasets)</span></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>                    <span class="at">mean_absences =</span> <span class="fu">mean</span>(new_absences, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>                    <span class="at">median_absences =</span> <span class="fu">median</span>(new_absences, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sd_absences =</span> <span class="fu">sd</span>(new_absences, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>                    <span class="at">IQR_absences =</span> <span class="fu">IQR</span>(new_absences, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>                   )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>two_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 14
# Groups:   sex [2]
  sex   school mean_G2 median_G2 sd_G2 IQR_G2 mean_age median_age sd_age IQR_age
  &lt;fct&gt; &lt;fct&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
1 F     GP        11.9      12    2.60   3        16.5         16  1.03        1
2 F     MS        11.2      11.5  3.10   3.5      17.7         18  0.577       1
3 M     GP        12.1      12    2.71   3.88     16.3         16  1.16        2
4 M     MS        10.7      11.2  3.26   5        18           18  0.603       0
# ℹ 4 more variables: mean_absences &lt;dbl&gt;, median_absences &lt;dbl&gt;,
#   sd_absences &lt;dbl&gt;, IQR_absences &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>Correlation matrix of all numeric variables.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>numeric_d1 <span class="ot">&lt;-</span> final_d1 <span class="sc">|&gt;</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric))</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>num_cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(numeric_d1)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>num_cor_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    age         Medu         Fedu   traveltime    studytime
age         1.000000000 -0.100949786 -0.107245313  0.160281754  0.043881028
Medu       -0.100949786  1.000000000  0.621523869 -0.218794954  0.045425978
Fedu       -0.107245313  0.621523869  1.000000000 -0.193978042 -0.039289626
traveltime  0.160281754 -0.218794954 -0.193978042  1.000000000 -0.103243249
studytime   0.043881028  0.045425978 -0.039289626 -0.103243249  1.000000000
failures    0.243429617 -0.125608045 -0.157496645  0.104521138 -0.179515785
famrel      0.049940980 -0.067657746 -0.047260992 -0.027275744  0.001381660
freetime   -0.045824466  0.004013326 -0.001258667 -0.055899592 -0.091829632
goout       0.150794790  0.065832096  0.050593936  0.006559725 -0.009403345
Dalc        0.113952023  0.062866542  0.039126588  0.161272613 -0.172278644
Walc        0.156817685 -0.004099434  0.023315814  0.105381347 -0.232402574
health     -0.113225976 -0.011497172  0.067152933  0.020869407 -0.040979063
absences.x  0.143925170  0.099832689  0.024617771 -0.001464243 -0.082387919
G1.x       -0.110379348  0.193071603  0.175557917 -0.088080745  0.125691378
G2.x       -0.186187399  0.188735230  0.150418214 -0.184594967  0.089030600
G3.x       -0.206031862  0.187754424  0.141990610 -0.165110961  0.045402243
absences.y  0.047331821  0.063530536  0.086614161  0.054308059 -0.134969383
G1.y       -0.050549678  0.181423706  0.115531025 -0.178191662  0.229739293
G2.y        0.029366456  0.189642017  0.136994424 -0.179611557  0.231059730
G3.y       -0.009103257  0.158979933  0.107807478 -0.153616466  0.238553746
              failures      famrel     freetime        goout        Dalc
age         0.24342962  0.04994098 -0.045824466  0.150794790  0.11395202
Medu       -0.12560804 -0.06765775  0.004013326  0.065832096  0.06286654
Fedu       -0.15749664 -0.04726099 -0.001258667  0.050593936  0.03912659
traveltime  0.10452114 -0.02727574 -0.055899592  0.006559725  0.16127261
studytime  -0.17951579  0.00138166 -0.091829632 -0.009403345 -0.17227864
failures    1.00000000  0.09437401  0.089757964  0.097119445  0.16213974
famrel      0.09437401  1.00000000  0.090946059  0.033058834 -0.05737989
freetime    0.08975796  0.09094606  1.000000000  0.243271162  0.20497133
goout       0.09711944  0.03305883  0.243271162  1.000000000  0.25703214
Dalc        0.16213974 -0.05737989  0.204971335  0.257032140  1.00000000
Walc        0.16736348 -0.12634267  0.119021094  0.378591514  0.64989386
health      0.04225577  0.13959656  0.070864701 -0.049000564  0.05996329
absences.x  0.12006863 -0.04806901 -0.046300383  0.078848996  0.15159884
G1.x       -0.19581035 -0.05618075 -0.017100766 -0.115882796 -0.09641793
G2.x       -0.16669179 -0.08710139 -0.029677027 -0.158978350 -0.05916707
G3.x       -0.14303203 -0.01797570 -0.006516202 -0.118423233 -0.04696434
absences.y  0.13424264 -0.02955203 -0.011429255  0.128521823  0.10753855
G1.y       -0.26927657 -0.06419546 -0.085629896 -0.071905764 -0.23398211
G2.y       -0.26992597 -0.02441686 -0.087231866 -0.091151551 -0.25300707
G3.y       -0.32775690 -0.01282948 -0.110638817 -0.073423265 -0.27992305
                   Walc       health   absences.x        G1.x        G2.x
age         0.156817685 -0.113225976  0.143925170 -0.11037935 -0.18618740
Medu       -0.004099434 -0.011497172  0.099832689  0.19307160  0.18873523
Fedu        0.023315814  0.067152933  0.024617771  0.17555792  0.15041821
traveltime  0.105381347  0.020869407 -0.001464243 -0.08808075 -0.18459497
studytime  -0.232402574 -0.040979063 -0.082387919  0.12569138  0.08903060
failures    0.167363479  0.042255769  0.120068630 -0.19581035 -0.16669179
famrel     -0.126342672  0.139596565 -0.048069014 -0.05618075 -0.08710139
freetime    0.119021094  0.070864701 -0.046300383 -0.01710077 -0.02967703
goout       0.378591514 -0.049000564  0.078848996 -0.11588280 -0.15897835
Dalc        0.649893859  0.059963287  0.151598836 -0.09641793 -0.05916707
Walc        1.000000000  0.070450703  0.208026186 -0.07964360 -0.06540510
health      0.070450703  1.000000000  0.012122515 -0.06155381 -0.07666718
absences.x  0.208026186  0.012122515  1.000000000 -0.06946116 -0.07580245
G1.x       -0.079643599 -0.061553810 -0.069461164  1.00000000  0.86588796
G2.x       -0.065405098 -0.076667185 -0.075802450  0.86588796  1.00000000
G3.x       -0.027623053 -0.047513775 -0.028118470  0.81859418  0.91357599
absences.y  0.150366322 -0.001077612  0.563815592 -0.08760610 -0.12636236
G1.y       -0.158160549 -0.126244006 -0.092477610  0.59293522  0.54300736
G2.y       -0.183295800 -0.170419288 -0.145164017  0.59517224  0.56521350
G3.y       -0.182606733 -0.162249671 -0.135726385  0.54388734  0.49603265
                   G3.x   absences.y        G1.y        G2.y         G3.y
age        -0.206031862  0.047331821 -0.05054968  0.02936646 -0.009103257
Medu        0.187754424  0.063530536  0.18142371  0.18964202  0.158979933
Fedu        0.141990610  0.086614161  0.11553102  0.13699442  0.107807478
traveltime -0.165110961  0.054308059 -0.17819166 -0.17961156 -0.153616466
studytime   0.045402243 -0.134969383  0.22973929  0.23105973  0.238553746
failures   -0.143032028  0.134242644 -0.26927657 -0.26992597 -0.327756897
famrel     -0.017975700 -0.029552034 -0.06419546 -0.02441686 -0.012829483
freetime   -0.006516202 -0.011429255 -0.08562990 -0.08723187 -0.110638817
goout      -0.118423233  0.128521823 -0.07190576 -0.09115155 -0.073423265
Dalc       -0.046964337  0.107538550 -0.23398211 -0.25300707 -0.279923052
Walc       -0.027623053  0.150366322 -0.15816055 -0.18329580 -0.182606733
health     -0.047513775 -0.001077612 -0.12624401 -0.17041929 -0.162249671
absences.x -0.028118470  0.563815592 -0.09247761 -0.14516402 -0.135726385
G1.x        0.818594184 -0.087606100  0.59293522  0.59517224  0.543887345
G2.x        0.913575991 -0.126362360  0.54300736  0.56521350  0.496032649
G3.x        1.000000000 -0.116640460  0.52288461  0.54545279  0.475956497
absences.y -0.116640460  1.000000000 -0.09864117 -0.12070727 -0.071452010
G1.y        0.522884610 -0.098641173  1.00000000  0.88415041  0.825414320
G2.y        0.545452789 -0.120707273  0.88415041  1.00000000  0.894309821
G3.y        0.475956497 -0.071452010  0.82541432  0.89430982  1.000000000</code></pre>
</div>
</div>
<p><strong>Histogram of Age &amp; Sex</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span> final_d1 , <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">fill =</span> sex)) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Histogram of Age by Sex"</span>,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Sex"</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Homework5_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Kernel Density Plot</strong></p>
<p>#fix</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span> final_d1 , <span class="fu">aes</span>(<span class="at">x =</span> (G1.x<span class="sc">+</span>G1.y)<span class="sc">/</span><span class="dv">2</span>,<span class="at">color =</span>sex)) <span class="sc">+</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Kernel Density Plot of Mean of G1"</span>,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Mean of G1 values"</span>,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">color=</span><span class="st">"Sex"</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Homework5_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Boxplot of two numerical variables w/ categorical</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span> final_d1 , <span class="fu">aes</span>(<span class="at">x =</span> age,<span class="at">y=</span>(G2.x<span class="sc">+</span>G2.y)<span class="sc">/</span><span class="dv">2</span>, <span class="at">fill=</span>sex)) <span class="sc">+</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Boxplot of Age by Sex"</span>,</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y=</span><span class="st">"Mean of G2"</span>,</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill=</span><span class="st">"Sex"</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Homework5_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Scatterplot #1</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(final_d1,  <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> (G3.x<span class="sc">+</span>G3.y)<span class="sc">/</span><span class="dv">2</span>, <span class="at">color =</span> sex) ) <span class="sc">+</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> <span class="st">"jitter"</span>) <span class="sc">+</span> </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Scatterplot of G3 vs. Age with Sex"</span>,</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mean of G3"</span>,</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Sex"</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Homework5_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Scatterplot #2</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(final_d1,  <span class="fu">aes</span>(<span class="at">x =</span> Medu, <span class="at">y =</span> (G3.x<span class="sc">+</span>G3.y)<span class="sc">/</span><span class="dv">2</span>, <span class="at">color =</span> reason) ) <span class="sc">+</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> <span class="st">"jitter"</span>) <span class="sc">+</span> </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Scatterplot of G3 vs. Male Education classified by Reason"</span>,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Male Education"</span>,</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mean of G3"</span>,</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Sex"</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Homework5_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Faceted Scatterplot #1</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(final_d1, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> (G3.x<span class="sc">+</span>G3.y)<span class="sc">/</span><span class="dv">2</span>, <span class="at">color =</span> sex)) <span class="sc">+</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position=</span><span class="st">"jitter"</span>) <span class="sc">+</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Scatterplot of G3 vs. Age with Sex, Faceted by School"</span>,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"G3"</span>,</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Sex"</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> school)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Homework5_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Faceted Scatterplot #2</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(final_d1, <span class="fu">aes</span>(<span class="at">x =</span> Medu, <span class="at">y =</span> (G3.x<span class="sc">+</span>G3.y)<span class="sc">/</span><span class="dv">2</span>, <span class="at">color =</span> sex)) <span class="sc">+</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position=</span><span class="st">"jitter"</span>) <span class="sc">+</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Scatterplot of G3.x vs. Male Education with Sex, Faceted by Reason"</span>,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"G3"</span>,</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Sex"</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> reason)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Homework5_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Faceting Two Categorical Variables</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(final_d1, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> (G3.x<span class="sc">+</span>G3.y)<span class="sc">/</span><span class="dv">2</span>, <span class="at">color =</span> sex)) <span class="sc">+</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position=</span><span class="st">"jitter"</span>) <span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Scatterplot of G3 vs. Age with Sex, Faceted by School and Sex"</span>,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"G3"</span>,</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Sex"</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> school <span class="sc">~</span> sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Homework5_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>